# NTP hostname or IP
ntp_server: 0.asia.pool.ntp.org

# Perform package update
pkg_update: no

rgw_vip: 172.20.23.160

haproxy_backend_servers:
 - name: ceph2-mon004
   address: 172.20.23.154
 - name: ceph2-mon005
   address: 172.20.23.124
 - name: ceph2-mon006
   address: 172.20.23.221

keepalived_master: ceph2-mon004
keepalived_master_priority: 110

