---
- hosts: all
  tasks:
  - name: Check current kernel version
    command: uname -r
    register: old_kernel_result

  - name: Set default kernel with targeted version
    shell: grubby --set-default "/boot/vmlinuz-{{ target_version }}.x86_64"

  - name: Reboot the server 
    reboot: 
      reboot_timeout: 300
    when: reboot == "yes"

  - name: Check new kernel version
    command: uname -r
    register: new_kernel_result

  - name: Remove previous kernel
    yum: 
      name: "kernel*-{{ old_kernel_result.stdout }}"
      state: absent
    when: (delete_previous_kernel == "yes") and (old_kernel_result.stdout != new_kernel_result.stdout)

  - name: Compare the kernel version
    debug: 
      msg: 
      - " Previous kernel version: {{ old_kernel_result.stdout }}"
      - " Rollbacked kernel version: {{ new_kernel_result.stdout }}"
