---
# This playbook is only for LGCNS environment
# created by hukim
#
- name: Install haproxy and keepalived
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - haproxy
    - keepalived
  
- name: Make sure if haproxy and keepalived are stoped
  service:
    name: "{{ item }}"
    state: stopped
    enabled: true
  with_items:
    - haproxy
    - keepalived
    
- name: Configure haproxy
  template:
    dest: /etc/haproxy/haproxy.cfg
    src: ../templates/haproxy.cfg.j2
    owner: root
    group: root
    mode: 0644
    
- name: Configure keepalived
  template:
    dest: /etc/keepalived/keepalived.conf
    src: ../templates/keepalived.conf.j2
    owner: root
    group: root
    mode: 0644

- name: Set kernel parameters for keepalived
  sysctl:
    name: "{{ item.param }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
    - { param: 'net.ipv4.ip_forward', value: '1' }
    - { param: 'net.ipv4.ip_nonlocal_bind', value: '1' }

- name: Set firewall for Keepalived
  firewalld: 
    state: enabled
    rich_rule: 'rule protocol value="vrrp" accept'
    permanent: true
    immediate: true

- name: Make sure if haproxy and keepalived are up and running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - haproxy
    - keepalived
