---
- name: Make sure if firewalld is up and running
  service:
    name: firewalld
    state: started
    enabled: true
    
- name: Set firewall policy for OSD
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - 6800-7300/tcp
  when:  (groups['osds'] is defined) and (ansible_hostname in groups['osds'])
    
- name: Set firewall policy for MON
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - 6789/tcp
    - 8002/tcp
  when: (groups['mons'] is defined) and (ansible_hostname in groups['mons'])

- name: Set firewall policy for RGWS
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - 7480/tcp
    - 80/tcp
    - 443/tcp
  when: (groups['rgws'] is defined) and (ansible_hostname in groups['rgws'])
